//
// Created by LaoZhu on 2022/3/27.
//

#ifndef MAIN_C_FORM_CALIBRATE_FORM_CALIBRATE_TOUCH_FORM_H_
#define MAIN_C_FORM_CALIBRATE_FORM_CALIBRATE_TOUCH_FORM_H_

void gui_calibrate_touch_form_init(void);

#endif //MAIN_C_FORM_CALIBRATE_FORM_CALIBRATE_TOUCH_FORM_H_
