name: KiCAD Exports

on:
  push:
    paths:
    - '**.sch'
    - '**.kicad_pcb'

jobs:
  export:
    runs-on: [ self-hosted, linux, x64 ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Configure CMake
        run: |
          PATH="$PATH:/opt/gcc-arm-none-eabi/bin" && echo $PATH
